# -------------- uris ------------------
# enterprise service bus
jboss:
  scheme: http
  host: 172.26.9.65
  port: 7171
  digitalizacion:
    context-path: /BsfPortalSucursalesDigitalizacion
    uri: ${jboss.scheme}://${jboss.host}:${jboss.port}${jboss.digitalizacion.context-path}/

# back-end services

wso2:
  scheme: http
  esb:
    host: 192.168.17.90
    port: 8305
    wsBsfDigitalizacion:
      context-path: /wsBsfDigitalizacion
      identificationImage: ${wso2.scheme}://${wso2.esb.host}:${wso2.esb.port}${wso2.esb.wsBsfDigitalizacion.context-path}/ConsultaDocumentoId
    wsBsfOperacionesSucursales:
      context-path: /wsBsfOperacionesSucursales
      encrypt: ${wso2.scheme}://${wso2.esb.host}:${wso2.esb.port}${wso2.esb.wsBsfOperacionesSucursales.context-path}/encrypt
      decrypt: ${wso2.scheme}://${wso2.esb.host}:${wso2.esb.port}${wso2.esb.wsBsfOperacionesSucursales.context-path}/decrypt

      
spring:
  jmx:
    enabled: false
  sqlserver:
    console:
      enabled: true
      path: /sqlserver-console
  datasource:
      url: jdbc:sqlserver://172.26.9.103;databaseName=BsfAcnSucursales
      username: usrBsfWeb
      password: Bansefi#2016
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: none
      
scheduled:
  temporal:
    path: C:\ETL
  cron-expression:
    medios-pago:
      entrada: "0 30 */2 * * *"
      salida:  "0 0 */2 * * *"